### ISSUE TITLE
Erro de não salvar endereço do pedido

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-mandae#5]
Ao gerar o pedido, não é salvo no mesmo o endereço do destinatário, apenas o cep de destino.

**Comment by leomp12** [comment]
@thiagoabreudev consegue dar uma olhada nisso por favor?

**Comment by matheusgnreis** [comment]
https://github.com/ecomplus/app-mandae/pull/4
Até coloquei isso aqui, talvez seja só isso

**Comment by leomp12** [comment]
@matheusgnreis sim, eu não tinha visto a PR antes, mas pedi o review do @thiagoabreudev lá sendo ele o codeowner aqui
